--
-- packages/places/sql/pl_countries-load.sql
--
-- @author jmileham@arsdigita.com
-- @creation-date 2000-12-14
-- @cvs-id $Id$
--

-- data loading pl/sql script generated by ctl-convert.pl

declare
 tempval acs_objects.object_id%TYPE;
begin

 tempval :=
  pl_country.new(
    iso => 'ad',
    country_name => 'Andorra'
  );

 tempval :=
  pl_country.new(
    iso => 'ae',
    country_name => 'United Arab Emirates'
  );

 tempval :=
  pl_country.new(
    iso => 'af',
    country_name => 'Afghanistan'
  );

 tempval :=
  pl_country.new(
    iso => 'ag',
    country_name => 'Antigua and Barbuda'
  );

 tempval :=
  pl_country.new(
    iso => 'ai',
    country_name => 'Anguilla'
  );

 tempval :=
  pl_country.new(
    iso => 'al',
    country_name => 'Albania'
  );

 tempval :=
  pl_country.new(
    iso => 'am',
    country_name => 'Armenia'
  );

 tempval :=
  pl_country.new(
    iso => 'an',
    country_name => 'Netherlands Antilles'
  );

 tempval :=
  pl_country.new(
    iso => 'ao',
    country_name => 'Angola'
  );

 tempval :=
  pl_country.new(
    iso => 'aq',
    country_name => 'Antarctica'
  );

 tempval :=
  pl_country.new(
    iso => 'ar',
    country_name => 'Argentina'
  );

 tempval :=
  pl_country.new(
    iso => 'as',
    country_name => 'American Samoa'
  );

 tempval :=
  pl_country.new(
    iso => 'at',
    country_name => 'Austria'
  );

 tempval :=
  pl_country.new(
    iso => 'au',
    country_name => 'Australia'
  );

 tempval :=
  pl_country.new(
    iso => 'aw',
    country_name => 'Aruba'
  );

 tempval :=
  pl_country.new(
    iso => 'az',
    country_name => 'Azerbaijan'
  );

 tempval :=
  pl_country.new(
    iso => 'ba',
    country_name => 'Bosnia and Herzegovina'
  );

 tempval :=
  pl_country.new(
    iso => 'bb',
    country_name => 'Barbados'
  );

 tempval :=
  pl_country.new(
    iso => 'bd',
    country_name => 'Bangladesh'
  );

 tempval :=
  pl_country.new(
    iso => 'be',
    country_name => 'Belgium'
  );

 tempval :=
  pl_country.new(
    iso => 'bf',
    country_name => 'Burkina Faso'
  );

 tempval :=
  pl_country.new(
    iso => 'bg',
    country_name => 'Bulgaria'
  );

 tempval :=
  pl_country.new(
    iso => 'bh',
    country_name => 'Bahrain'
  );

 tempval :=
  pl_country.new(
    iso => 'bi',
    country_name => 'Burundi'
  );

 tempval :=
  pl_country.new(
    iso => 'bj',
    country_name => 'Benin'
  );

 tempval :=
  pl_country.new(
    iso => 'bm',
    country_name => 'Bermuda'
  );

 tempval :=
  pl_country.new(
    iso => 'bn',
    country_name => 'Brunei Darussalam'
  );

 tempval :=
  pl_country.new(
    iso => 'bo',
    country_name => 'Bolivia'
  );

 tempval :=
  pl_country.new(
    iso => 'br',
    country_name => 'Brazil'
  );

 tempval :=
  pl_country.new(
    iso => 'bs',
    country_name => 'Bahamas'
  );

 tempval :=
  pl_country.new(
    iso => 'bt',
    country_name => 'Bhutan'
  );

 tempval :=
  pl_country.new(
    iso => 'bv',
    country_name => 'Bouvet Island'
  );

 tempval :=
  pl_country.new(
    iso => 'bw',
    country_name => 'Botswana'
  );

 tempval :=
  pl_country.new(
    iso => 'by',
    country_name => 'Belarus'
  );

 tempval :=
  pl_country.new(
    iso => 'bz',
    country_name => 'Belize'
  );

 tempval :=
  pl_country.new(
    iso => 'ca',
    country_name => 'Canada'
  );

 tempval :=
  pl_country.new(
    iso => 'cc',
    country_name => 'Cocos (Keeling) Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'cf',
    country_name => 'Central African Republic'
  );

 tempval :=
  pl_country.new(
    iso => 'cg',
    country_name => 'Congo'
  );

 tempval :=
  pl_country.new(
    iso => 'ch',
    country_name => 'Switzerland'
  );

 tempval :=
  pl_country.new(
    iso => 'ck',
    country_name => 'Cook Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'cl',
    country_name => 'Chile'
  );

 tempval :=
  pl_country.new(
    iso => 'cm',
    country_name => 'Cameroon'
  );

 tempval :=
  pl_country.new(
    iso => 'cn',
    country_name => 'China'
  );

 tempval :=
  pl_country.new(
    iso => 'co',
    country_name => 'Colombia'
  );

 tempval :=
  pl_country.new(
    iso => 'cr',
    country_name => 'Costa Rica'
  );

 tempval :=
  pl_country.new(
    iso => 'cs',
    country_name => 'Czechoslovakia (former)'
  );

 tempval :=
  pl_country.new(
    iso => 'cu',
    country_name => 'Cuba'
  );

 tempval :=
  pl_country.new(
    iso => 'cv',
    country_name => 'Cape Verde'
  );

 tempval :=
  pl_country.new(
    iso => 'cx',
    country_name => 'Christmas Island'
  );

 tempval :=
  pl_country.new(
    iso => 'cy',
    country_name => 'Cyprus'
  );

 tempval :=
  pl_country.new(
    iso => 'cz',
    country_name => 'Czech Republic'
  );

 tempval :=
  pl_country.new(
    iso => 'de',
    country_name => 'Germany'
  );

 tempval :=
  pl_country.new(
    iso => 'dj',
    country_name => 'Djibouti'
  );

 tempval :=
  pl_country.new(
    iso => 'dk',
    country_name => 'Denmark'
  );

 tempval :=
  pl_country.new(
    iso => 'dm',
    country_name => 'Dominica'
  );

 tempval :=
  pl_country.new(
    iso => 'do',
    country_name => 'Dominican Republic'
  );

 tempval :=
  pl_country.new(
    iso => 'dz',
    country_name => 'Algeria'
  );

 tempval :=
  pl_country.new(
    iso => 'ec',
    country_name => 'Ecuador'
  );

 tempval :=
  pl_country.new(
    iso => 'ee',
    country_name => 'Estonia'
  );

 tempval :=
  pl_country.new(
    iso => 'eg',
    country_name => 'Egypt'
  );

 tempval :=
  pl_country.new(
    iso => 'eh',
    country_name => 'Western Sahara'
  );

 tempval :=
  pl_country.new(
    iso => 'er',
    country_name => 'Eritrea'
  );

 tempval :=
  pl_country.new(
    iso => 'es',
    country_name => 'Spain'
  );

 tempval :=
  pl_country.new(
    iso => 'et',
    country_name => 'Ethiopia'
  );

 tempval :=
  pl_country.new(
    iso => 'fi',
    country_name => 'Finland'
  );

 tempval :=
  pl_country.new(
    iso => 'fj',
    country_name => 'Fiji'
  );

 tempval :=
  pl_country.new(
    iso => 'fk',
    country_name => 'Falkland Islands (Malvinas)'
  );

 tempval :=
  pl_country.new(
    iso => 'fm',
    country_name => 'Micronesia'
  );

 tempval :=
  pl_country.new(
    iso => 'fo',
    country_name => 'Faroe Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'fr',
    country_name => 'France'
  );

 tempval :=
  pl_country.new(
    iso => 'fx',
    country_name => 'France, Metropolitan'
  );

 tempval :=
  pl_country.new(
    iso => 'ga',
    country_name => 'Gabon'
  );

 tempval :=
  pl_country.new(
    iso => 'gb',
    country_name => 'Great Britain (UK)'
  );

 tempval :=
  pl_country.new(
    iso => 'gd',
    country_name => 'Grenada'
  );

 tempval :=
  pl_country.new(
    iso => 'ge',
    country_name => 'Georgia'
  );

 tempval :=
  pl_country.new(
    iso => 'gf',
    country_name => 'French Guiana'
  );

 tempval :=
  pl_country.new(
    iso => 'gh',
    country_name => 'Ghana'
  );

 tempval :=
  pl_country.new(
    iso => 'gi',
    country_name => 'Gibraltar'
  );

 tempval :=
  pl_country.new(
    iso => 'gl',
    country_name => 'Greenland'
  );

 tempval :=
  pl_country.new(
    iso => 'gm',
    country_name => 'Gambia'
  );

 tempval :=
  pl_country.new(
    iso => 'gn',
    country_name => 'Guinea'
  );

 tempval :=
  pl_country.new(
    iso => 'gp',
    country_name => 'Guadeloupe'
  );

 tempval :=
  pl_country.new(
    iso => 'gq',
    country_name => 'Equatorial Guinea'
  );

 tempval :=
  pl_country.new(
    iso => 'gr',
    country_name => 'Greece'
  );

 tempval :=
  pl_country.new(
    iso => 'gs',
    country_name => 'S. Georgia and S. Sandwich Isls.'
  );

 tempval :=
  pl_country.new(
    iso => 'gt',
    country_name => 'Guatemala'
  );

 tempval :=
  pl_country.new(
    iso => 'gu',
    country_name => 'Guam'
  );

 tempval :=
  pl_country.new(
    iso => 'gw',
    country_name => 'Guinea-Bissau'
  );

 tempval :=
  pl_country.new(
    iso => 'gy',
    country_name => 'Guyana'
  );

 tempval :=
  pl_country.new(
    iso => 'hk',
    country_name => 'Hong Kong'
  );

 tempval :=
  pl_country.new(
    iso => 'hm',
    country_name => 'Heard and McDonald Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'hn',
    country_name => 'Honduras'
  );

 tempval :=
  pl_country.new(
    iso => 'hr',
    country_name => 'Croatia (Hrvatska)'
  );

 tempval :=
  pl_country.new(
    iso => 'ht',
    country_name => 'Haiti'
  );

 tempval :=
  pl_country.new(
    iso => 'hu',
    country_name => 'Hungary'
  );

 tempval :=
  pl_country.new(
    iso => 'id',
    country_name => 'Indonesia'
  );

 tempval :=
  pl_country.new(
    iso => 'ie',
    country_name => 'Ireland'
  );

 tempval :=
  pl_country.new(
    iso => 'il',
    country_name => 'Israel'
  );

 tempval :=
  pl_country.new(
    iso => 'in',
    country_name => 'India'
  );

 tempval :=
  pl_country.new(
    iso => 'io',
    country_name => 'British Indian Ocean Territory'
  );

 tempval :=
  pl_country.new(
    iso => 'iq',
    country_name => 'Iraq'
  );

 tempval :=
  pl_country.new(
    iso => 'ir',
    country_name => 'Iran'
  );

 tempval :=
  pl_country.new(
    iso => 'is',
    country_name => 'Iceland'
  );

 tempval :=
  pl_country.new(
    iso => 'it',
    country_name => 'Italy'
  );

 tempval :=
  pl_country.new(
    iso => 'jm',
    country_name => 'Jamaica'
  );

 tempval :=
  pl_country.new(
    iso => 'jo',
    country_name => 'Jordan'
  );

 tempval :=
  pl_country.new(
    iso => 'jp',
    country_name => 'Japan'
  );

 tempval :=
  pl_country.new(
    iso => 'ke',
    country_name => 'Kenya'
  );

 tempval :=
  pl_country.new(
    iso => 'kg',
    country_name => 'Kyrgyzstan'
  );

 tempval :=
  pl_country.new(
    iso => 'kh',
    country_name => 'Cambodia'
  );

 tempval :=
  pl_country.new(
    iso => 'ki',
    country_name => 'Kiribati'
  );

 tempval :=
  pl_country.new(
    iso => 'km',
    country_name => 'Comoros'
  );

 tempval :=
  pl_country.new(
    iso => 'kn',
    country_name => 'Saint Kitts and Nevis'
  );

 tempval :=
  pl_country.new(
    iso => 'kp',
    country_name => 'Korea (North)'
  );

 tempval :=
  pl_country.new(
    iso => 'kr',
    country_name => 'Korea (South)'
  );

 tempval :=
  pl_country.new(
    iso => 'kw',
    country_name => 'Kuwait'
  );

 tempval :=
  pl_country.new(
    iso => 'ky',
    country_name => 'Cayman Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'kz',
    country_name => 'Kazakhstan'
  );

 tempval :=
  pl_country.new(
    iso => 'la',
    country_name => 'Laos'
  );

 tempval :=
  pl_country.new(
    iso => 'lb',
    country_name => 'Lebanon'
  );

 tempval :=
  pl_country.new(
    iso => 'lc',
    country_name => 'Saint Lucia'
  );

 tempval :=
  pl_country.new(
    iso => 'li',
    country_name => 'Liechtenstein'
  );

 tempval :=
  pl_country.new(
    iso => 'lk',
    country_name => 'Sri Lanka'
  );

 tempval :=
  pl_country.new(
    iso => 'lr',
    country_name => 'Liberia'
  );

 tempval :=
  pl_country.new(
    iso => 'ls',
    country_name => 'Lesotho'
  );

 tempval :=
  pl_country.new(
    iso => 'lt',
    country_name => 'Lithuania'
  );

 tempval :=
  pl_country.new(
    iso => 'lu',
    country_name => 'Luxembourg'
  );

 tempval :=
  pl_country.new(
    iso => 'lv',
    country_name => 'Latvia'
  );

 tempval :=
  pl_country.new(
    iso => 'ly',
    country_name => 'Libya'
  );

 tempval :=
  pl_country.new(
    iso => 'ma',
    country_name => 'Morocco'
  );

 tempval :=
  pl_country.new(
    iso => 'mc',
    country_name => 'Monaco'
  );

 tempval :=
  pl_country.new(
    iso => 'md',
    country_name => 'Moldova'
  );

 tempval :=
  pl_country.new(
    iso => 'mg',
    country_name => 'Madagascar'
  );

 tempval :=
  pl_country.new(
    iso => 'mh',
    country_name => 'Marshall Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'mk',
    country_name => 'Macedonia'
  );

 tempval :=
  pl_country.new(
    iso => 'ml',
    country_name => 'Mali'
  );

 tempval :=
  pl_country.new(
    iso => 'mm',
    country_name => 'Myanmar'
  );

 tempval :=
  pl_country.new(
    iso => 'mn',
    country_name => 'Mongolia'
  );

 tempval :=
  pl_country.new(
    iso => 'mo',
    country_name => 'Macau'
  );

 tempval :=
  pl_country.new(
    iso => 'mp',
    country_name => 'Northern Mariana Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'mq',
    country_name => 'Martinique'
  );

 tempval :=
  pl_country.new(
    iso => 'mr',
    country_name => 'Mauritania'
  );

 tempval :=
  pl_country.new(
    iso => 'ms',
    country_name => 'Montserrat'
  );

 tempval :=
  pl_country.new(
    iso => 'mt',
    country_name => 'Malta'
  );

 tempval :=
  pl_country.new(
    iso => 'mu',
    country_name => 'Mauritius'
  );

 tempval :=
  pl_country.new(
    iso => 'mv',
    country_name => 'Maldives'
  );

 tempval :=
  pl_country.new(
    iso => 'mw',
    country_name => 'Malawi'
  );

 tempval :=
  pl_country.new(
    iso => 'mx',
    country_name => 'Mexico'
  );

 tempval :=
  pl_country.new(
    iso => 'my',
    country_name => 'Malaysia'
  );

 tempval :=
  pl_country.new(
    iso => 'mz',
    country_name => 'Mozambique'
  );

 tempval :=
  pl_country.new(
    iso => 'na',
    country_name => 'Namibia'
  );

 tempval :=
  pl_country.new(
    iso => 'nc',
    country_name => 'New Caledonia'
  );

 tempval :=
  pl_country.new(
    iso => 'ne',
    country_name => 'Niger'
  );

 tempval :=
  pl_country.new(
    iso => 'nf',
    country_name => 'Norfolk Island'
  );

 tempval :=
  pl_country.new(
    iso => 'ng',
    country_name => 'Nigeria'
  );

 tempval :=
  pl_country.new(
    iso => 'ni',
    country_name => 'Nicaragua'
  );

 tempval :=
  pl_country.new(
    iso => 'nl',
    country_name => 'Netherlands'
  );

 tempval :=
  pl_country.new(
    iso => 'no',
    country_name => 'Norway'
  );

 tempval :=
  pl_country.new(
    iso => 'np',
    country_name => 'Nepal'
  );

 tempval :=
  pl_country.new(
    iso => 'nr',
    country_name => 'Nauru'
  );

 tempval :=
  pl_country.new(
    iso => 'nt',
    country_name => 'Neutral Zone'
  );

 tempval :=
  pl_country.new(
    iso => 'nu',
    country_name => 'Niue'
  );

 tempval :=
  pl_country.new(
    iso => 'nz',
    country_name => 'New Zealand (Aotearoa)'
  );

 tempval :=
  pl_country.new(
    iso => 'om',
    country_name => 'Oman'
  );

 tempval :=
  pl_country.new(
    iso => 'pa',
    country_name => 'Panama'
  );

 tempval :=
  pl_country.new(
    iso => 'pe',
    country_name => 'Peru'
  );

 tempval :=
  pl_country.new(
    iso => 'pf',
    country_name => 'French Polynesia'
  );

 tempval :=
  pl_country.new(
    iso => 'pg',
    country_name => 'Papua New Guinea'
  );

 tempval :=
  pl_country.new(
    iso => 'ph',
    country_name => 'Philippines'
  );

 tempval :=
  pl_country.new(
    iso => 'pk',
    country_name => 'Pakistan'
  );

 tempval :=
  pl_country.new(
    iso => 'pl',
    country_name => 'Poland'
  );

 tempval :=
  pl_country.new(
    iso => 'pm',
    country_name => 'St. Pierre and Miquelon'
  );

 tempval :=
  pl_country.new(
    iso => 'pn',
    country_name => 'Pitcairn'
  );

 tempval :=
  pl_country.new(
    iso => 'pr',
    country_name => 'Puerto Rico'
  );

 tempval :=
  pl_country.new(
    iso => 'pt',
    country_name => 'Portugal'
  );

 tempval :=
  pl_country.new(
    iso => 'pw',
    country_name => 'Palau'
  );

 tempval :=
  pl_country.new(
    iso => 'py',
    country_name => 'Paraguay'
  );

 tempval :=
  pl_country.new(
    iso => 'qa',
    country_name => 'Qatar'
  );

 tempval :=
  pl_country.new(
    iso => 're',
    country_name => 'Reunion'
  );

 tempval :=
  pl_country.new(
    iso => 'ro',
    country_name => 'Romania'
  );

 tempval :=
  pl_country.new(
    iso => 'ru',
    country_name => 'Russian Federation'
  );

 tempval :=
  pl_country.new(
    iso => 'rw',
    country_name => 'Rwanda'
  );

 tempval :=
  pl_country.new(
    iso => 'sa',
    country_name => 'Saudi Arabia'
  );

 tempval :=
  pl_country.new(
    iso => 'sb',
    country_name => 'Solomon Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'sc',
    country_name => 'Seychelles'
  );

 tempval :=
  pl_country.new(
    iso => 'sd',
    country_name => 'Sudan'
  );

 tempval :=
  pl_country.new(
    iso => 'se',
    country_name => 'Sweden'
  );

 tempval :=
  pl_country.new(
    iso => 'sg',
    country_name => 'Singapore'
  );

 tempval :=
  pl_country.new(
    iso => 'sh',
    country_name => 'St. Helena'
  );

 tempval :=
  pl_country.new(
    iso => 'si',
    country_name => 'Slovenia'
  );

 tempval :=
  pl_country.new(
    iso => 'sj',
    country_name => 'Svalbard and Jan Mayen Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'sk',
    country_name => 'Slovak Republic'
  );

 tempval :=
  pl_country.new(
    iso => 'sl',
    country_name => 'Sierra Leone'
  );

 tempval :=
  pl_country.new(
    iso => 'sm',
    country_name => 'San Marino'
  );

 tempval :=
  pl_country.new(
    iso => 'sn',
    country_name => 'Senegal'
  );

 tempval :=
  pl_country.new(
    iso => 'so',
    country_name => 'Somalia'
  );

 tempval :=
  pl_country.new(
    iso => 'sr',
    country_name => 'Suriname'
  );

 tempval :=
  pl_country.new(
    iso => 'st',
    country_name => 'Sao Tome and Principe'
  );

 tempval :=
  pl_country.new(
    iso => 'su',
    country_name => 'USSR (former)'
  );

 tempval :=
  pl_country.new(
    iso => 'sv',
    country_name => 'El Salvador'
  );

 tempval :=
  pl_country.new(
    iso => 'sy',
    country_name => 'Syria'
  );

 tempval :=
  pl_country.new(
    iso => 'sz',
    country_name => 'Swaziland'
  );

 tempval :=
  pl_country.new(
    iso => 'tc',
    country_name => 'Turks and Caicos Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'td',
    country_name => 'Chad'
  );

 tempval :=
  pl_country.new(
    iso => 'tf',
    country_name => 'French Southern Territories'
  );

 tempval :=
  pl_country.new(
    iso => 'tg',
    country_name => 'Togo'
  );

 tempval :=
  pl_country.new(
    iso => 'th',
    country_name => 'Thailand'
  );

 tempval :=
  pl_country.new(
    iso => 'tj',
    country_name => 'Tajikistan'
  );

 tempval :=
  pl_country.new(
    iso => 'tk',
    country_name => 'Tokelau'
  );

 tempval :=
  pl_country.new(
    iso => 'tm',
    country_name => 'Turkmenistan'
  );

 tempval :=
  pl_country.new(
    iso => 'tn',
    country_name => 'Tunisia'
  );

 tempval :=
  pl_country.new(
    iso => 'to',
    country_name => 'Tonga'
  );

 tempval :=
  pl_country.new(
    iso => 'tp',
    country_name => 'East Timor'
  );

 tempval :=
  pl_country.new(
    iso => 'tr',
    country_name => 'Turkey'
  );

 tempval :=
  pl_country.new(
    iso => 'tt',
    country_name => 'Trinidad and Tobago'
  );

 tempval :=
  pl_country.new(
    iso => 'tv',
    country_name => 'Tuvalu'
  );

 tempval :=
  pl_country.new(
    iso => 'tw',
    country_name => 'Taiwan'
  );

 tempval :=
  pl_country.new(
    iso => 'tz',
    country_name => 'Tanzania'
  );

 tempval :=
  pl_country.new(
    iso => 'ua',
    country_name => 'Ukraine'
  );

 tempval :=
  pl_country.new(
    iso => 'ug',
    country_name => 'Uganda'
  );

 tempval :=
  pl_country.new(
    iso => 'uk',
    country_name => 'United Kingdom'
  );

 tempval :=
  pl_country.new(
    iso => 'um',
    country_name => 'US Minor Outlying Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'us',
    country_name => 'United States'
  );

 tempval :=
  pl_country.new(
    iso => 'uy',
    country_name => 'Uruguay'
  );

 tempval :=
  pl_country.new(
    iso => 'uz',
    country_name => 'Uzbekistan'
  );

 tempval :=
  pl_country.new(
    iso => 'va',
    country_name => 'Vatican City State (Holy See)'
  );

 tempval :=
  pl_country.new(
    iso => 'vc',
    country_name => 'Saint Vincent and the Grenadines'
  );

 tempval :=
  pl_country.new(
    iso => 've',
    country_name => 'Venezuela'
  );

 tempval :=
  pl_country.new(
    iso => 'vg',
    country_name => 'Virgin Islands (British)'
  );

 tempval :=
  pl_country.new(
    iso => 'vi',
    country_name => 'Virgin Islands (U.S.)'
  );

 tempval :=
  pl_country.new(
    iso => 'vn',
    country_name => 'Viet Nam'
  );

 tempval :=
  pl_country.new(
    iso => 'vu',
    country_name => 'Vanuatu'
  );

 tempval :=
  pl_country.new(
    iso => 'wf',
    country_name => 'Wallis and Futuna Islands'
  );

 tempval :=
  pl_country.new(
    iso => 'ws',
    country_name => 'Samoa'
  );

 tempval :=
  pl_country.new(
    iso => 'ye',
    country_name => 'Yemen'
  );

 tempval :=
  pl_country.new(
    iso => 'yt',
    country_name => 'Mayotte'
  );

 tempval :=
  pl_country.new(
    iso => 'yu',
    country_name => 'Yugoslavia'
  );

 tempval :=
  pl_country.new(
    iso => 'za',
    country_name => 'South Africa'
  );

 tempval :=
  pl_country.new(
    iso => 'zm',
    country_name => 'Zambia'
  );

 tempval :=
  pl_country.new(
    iso => 'zr',
    country_name => 'Zaire'
  );

 tempval :=
  pl_country.new(
    iso => 'zw',
    country_name => 'Zimbabwe'
  );

 commit;
end;
/
show errors
