--
-- packages/places/sql/pl_us_states-load.sql
--
-- @author jmileham@arsdigita.com
-- @creation-date 2000-12-14
-- @cvs-id $Id$
--

-- data loading pl/sql script generated by ctl-convert.pl

declare
 us_id	pl_countries.country_id%TYPE;
 tempval acs_objects.object_id%TYPE;
begin
 select country_id
   into us_id
   from pl_countries
  where iso = 'us';

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'AL',
    state_name => 'ALABAMA',
    fips_state_code => '01'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'AK',
    state_name => 'ALASKA',
    fips_state_code => '02'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'AZ',
    state_name => 'ARIZONA',
    fips_state_code => '04'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'AR',
    state_name => 'ARKANSAS',
    fips_state_code => '05'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'CA',
    state_name => 'CALIFORNIA',
    fips_state_code => '06'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'CO',
    state_name => 'COLORADO',
    fips_state_code => '08'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'CT',
    state_name => 'CONNECTICUT',
    fips_state_code => '09'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'DE',
    state_name => 'DELAWARE',
    fips_state_code => '10'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'DC',
    state_name => 'DISTRICT OF COLUMBIA',
    fips_state_code => '11'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'FL',
    state_name => 'FLORIDA',
    fips_state_code => '12'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'GA',
    state_name => 'GEORGIA',
    fips_state_code => '13'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'HI',
    state_name => 'HAWAII',
    fips_state_code => '15'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'ID',
    state_name => 'IDAHO',
    fips_state_code => '16'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'IL',
    state_name => 'ILLINOIS',
    fips_state_code => '17'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'IN',
    state_name => 'INDIANA',
    fips_state_code => '18'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'IA',
    state_name => 'IOWA',
    fips_state_code => '19'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'KS',
    state_name => 'KANSAS',
    fips_state_code => '20'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'KY',
    state_name => 'KENTUCKY',
    fips_state_code => '21'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'LA',
    state_name => 'LOUISIANA',
    fips_state_code => '22'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'ME',
    state_name => 'MAINE',
    fips_state_code => '23'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MD',
    state_name => 'MARYLAND',
    fips_state_code => '24'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MA',
    state_name => 'MASSACHUSETTS',
    fips_state_code => '25'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MI',
    state_name => 'MICHIGAN',
    fips_state_code => '26'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MN',
    state_name => 'MINNESOTA',
    fips_state_code => '27'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MS',
    state_name => 'MISSISSIPPI',
    fips_state_code => '28'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MO',
    state_name => 'MISSOURI',
    fips_state_code => '29'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MT',
    state_name => 'MONTANA',
    fips_state_code => '30'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'NE',
    state_name => 'NEBRASKA',
    fips_state_code => '31'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'NV',
    state_name => 'NEVADA',
    fips_state_code => '32'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'NH',
    state_name => 'NEW HAMPSHIRE',
    fips_state_code => '33'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'NJ',
    state_name => 'NEW JERSEY',
    fips_state_code => '34'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'NM',
    state_name => 'NEW MEXICO',
    fips_state_code => '35'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'NY',
    state_name => 'NEW YORK',
    fips_state_code => '36'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'NC',
    state_name => 'NORTH CAROLINA',
    fips_state_code => '37'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'ND',
    state_name => 'NORTH DAKOTA',
    fips_state_code => '38'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'OH',
    state_name => 'OHIO',
    fips_state_code => '39'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'OK',
    state_name => 'OKLAHOMA',
    fips_state_code => '40'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'OR',
    state_name => 'OREGON',
    fips_state_code => '41'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'PA',
    state_name => 'PENNSYLVANIA',
    fips_state_code => '42'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'RI',
    state_name => 'RHODE ISLAND',
    fips_state_code => '44'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'SC',
    state_name => 'SOUTH CAROLINA',
    fips_state_code => '45'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'SD',
    state_name => 'SOUTH DAKOTA',
    fips_state_code => '46'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'TN',
    state_name => 'TENNESSEE',
    fips_state_code => '47'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'TX',
    state_name => 'TEXAS',
    fips_state_code => '48'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'UT',
    state_name => 'UTAH',
    fips_state_code => '49'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'VT',
    state_name => 'VERMONT',
    fips_state_code => '50'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'VA',
    state_name => 'VIRGINIA',
    fips_state_code => '51'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'WA',
    state_name => 'WASHINGTON',
    fips_state_code => '53'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'WV',
    state_name => 'WEST VIRGINIA',
    fips_state_code => '54'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'WI',
    state_name => 'WISCONSIN',
    fips_state_code => '55'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'WY',
    state_name => 'WYOMING',
    fips_state_code => '56'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'AS',
    state_name => 'AMERICAN SAMOA',
    fips_state_code => '60'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'GU',
    state_name => 'GUAM',
    fips_state_code => '66'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MP',
    state_name => 'NORTHERN MARIANA ISLANDS',
    fips_state_code => '69'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'PR',
    state_name => 'PUERTO RICO',
    fips_state_code => '72'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'VI',
    state_name => 'VIRGIN ISLANDS',
    fips_state_code => '78'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'FM',
    state_name => 'FED. STATES OF MICRONESIA',
    fips_state_code => '64'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'UM',
    state_name => 'US MINOR OUTLYING ISLANDS',
    fips_state_code => '74'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '67',
    state_name => 'JOHNSTON ATOLL',
    fips_state_code => '67'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'MH',
    state_name => 'MARSHALL ISLANDS',
    fips_state_code => '68'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => 'PW',
    state_name => 'PALAU',
    fips_state_code => '70'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '71',
    state_name => 'MIDWAY ISLANDS',
    fips_state_code => '71'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '76',
    state_name => 'NAVASSA ISLAND',
    fips_state_code => '76'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '79',
    state_name => 'WAKE ISLAND',
    fips_state_code => '79'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '81',
    state_name => 'BAKER ISLAND',
    fips_state_code => '81'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '84',
    state_name => 'HOWLAND ISLAND',
    fips_state_code => '84'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '86',
    state_name => 'JARVIS ISLAND',
    fips_state_code => '86'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '89',
    state_name => 'KINGMAN REEF',
    fips_state_code => '89'
  );

 tempval :=
  pl_us_state.new(
    superplace_id => us_id,
    usps_abbrev => '95',
    state_name => 'PALMYRA ATOLL',
    fips_state_code => '95'
  );

 commit;
end;
/
show errors
